In [2]:
import numpy as np

In [3]:
def conv2d_single_channel(input_map, kernel, stride=1, padding=0):
    if padding > 0:
        input_map = np.pad(input_map, pad_width=padding, mode='constant', constant_values=0)
    k = kernel.shape[0]
    out_h = (input_map.shape[0] - k) // stride + 1
    out_w = (input_map.shape[1] - k) // stride + 1
    out = np.zeros((out_h, out_w), dtype=float)
    for i in range(out_h):
        for j in range(out_w):
            patch = input_map[i*stride:i*stride+k, j*stride:j*stride+k]
            out[i, j] = np.sum(patch * kernel)
    return out

In [4]:
I = np.array([
    [10,10,10, 0, 0, 0],
    [10,10,10, 0, 0, 0],
    [10,10,10, 0, 0, 0],
    [10,10,10,10,10,10],
    [10,10,10,10,10,10],
    [10,10,10,10,10,10]
], dtype=float)

k = np.array([[1,0,-1],[1,0,-1],[1,0,-1]], dtype=float)

In [5]:
configs = [
    ("stride=1, padding=0", 1, 0),
    ("stride=2, padding=0", 2, 0),
    ("stride=1, padding=1", 1, 1),
]

In [6]:
for desc, s, p in configs:
    out = conv2d_single_channel(I, k, stride=s, padding=p)
    print(f"\n{desc}: output shape = {out.shape}")
    print(out.astype(int)) 


stride=1, padding=0: output shape = (4, 4)
[[ 0 30 30  0]
 [ 0 20 20  0]
 [ 0 10 10  0]
 [ 0  0  0  0]]

stride=2, padding=0: output shape = (2, 2)
[[ 0 30]
 [ 0 10]]

stride=1, padding=1: output shape = (6, 6)
[[-20   0  20  20   0   0]
 [-30   0  30  30   0   0]
 [-30   0  20  20   0  10]
 [-30   0  10  10   0  20]
 [-30   0   0   0   0  30]
 [-20   0   0   0   0  20]]
